import { Jost } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";



const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700', '800']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <head>

        <script dangerouslySetInnerHTML={{
          __html: `
    (function() {
      const theme = localStorage.getItem('theme');
      if (theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
        document.documentElement.classList.add('dark');
      }
    })();
  `,
        }} />

      </head>

      <body
        className={`${jost.variable} antialiased`}
      >
        <Navbar />

        {children}

      </body>



    </html>
  );
}
